### ISSUE TITLE
Entering Mirza with a non-Kotla piece incorrectly ends the game

### ISSUE THREAD

**Issue by AlbertNewton** [SpookyScaryDev/Dastan#1]
When I enter the enemy Kotla with my own piece (not my Mirza), the game ends. This shouldn't happen; if I'm reading the documentation correctly, a player entering another player's Kotla should only end the game when the occupying piece is the Mirza.

**Comment by AlbertNewton** [comment]
![image](https://user-images.githubusercontent.com/42004388/235161588-4144347e-646b-4f43-806b-a2d93149f464.png)

**Comment by SpookyScaryDev** [comment]
Hey, sorry it took a while to get to this, I didn't realize I had notifications turned off :)
Should be fixed in the latest commit.
